name: CI

on:
  push:
    branches:
      - 3.x
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: src/LibVLCSharp/packages.lock.json
      # - name: Install dotnet workloads
      #   run: |
      #     dotnet workload install android
      #     dotnet workload install ios
      #     dotnet workload install macos
      #     dotnet workload install tvos
      - name: Install Cake
        run: dotnet tool install Cake.Tool --global
      - name: Build
        run: dotnet cake --target Build-only-libvlcsharp
        working-directory: buildsystem
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nugets
          path: nugets
          if-no-files-found: error
  
  test:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: src/LibVLCSharp/packages.lock.json
      - name: Install Cake
        run: dotnet tool install Cake.Tool --global
      - uses: actions/download-artifact@v4
      - name: Test
        run: dotnet cake --target Test
        working-directory: buildsystem
